# Generated by Django 6.0.4 on 2026-05-04 08:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Taom nomi')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('snack', 'Gazak'), ('any', 'Istalgan vaqt')], default='any', max_length=20, verbose_name='Taom turi')),
                ('calories_per_100g', models.FloatField(verbose_name='Kaloriya (100g uchun)')),
                ('protein_per_100g', models.FloatField(default=0, verbose_name='Oqsil (g/100g)')),
                ('fat_per_100g', models.FloatField(default=0, verbose_name="Yog' (g/100g)")),
                ('carbs_per_100g', models.FloatField(default=0, verbose_name='Uglevod (g/100g)')),
                ('default_portion_g', models.IntegerField(default=200, verbose_name='Standart porsiya (g)')),
                ('region', models.CharField(choices=[('toshkent', 'Toshkent'), ('samarqand', 'Samarqand'), ('buxoro', 'Buxoro'), ('fargona', "Farg'ona"), ('xorazm', 'Xorazm'), ('umumiy', "Umumiy O'zbek")], default='umumiy', max_length=50, verbose_name='Mintaqa')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('recipe_url', models.URLField(blank=True, verbose_name='Retsept havolasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='foods/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taom',
                'verbose_name_plural': 'Taomlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Nonushta'), ('lunch', 'Tushlik'), ('dinner', 'Kechki ovqat'), ('snack', 'Gazak')], max_length=20, verbose_name='Ovqat vaqti')),
                ('amount_g', models.FloatField(verbose_name='Miqdor (g)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='core.food')),
            ],
            options={
                'verbose_name': 'Ovqat jurnali',
                'verbose_name_plural': 'Ovqat jurnallari',
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.CreateModel(
            name='PhysicalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('walking', 'Yurish'), ('running', 'Yugurish'), ('cycling', 'Velosiped'), ('swimming', 'Suzish'), ('gym', 'Sport zali'), ('football', 'Futbol'), ('basketball', 'Basketbol'), ('yoga', 'Yoga'), ('other', 'Boshqa')], max_length=50, verbose_name='Faoliyat turi')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Davomiyligi (daqiqa)')),
                ('calories_burned', models.IntegerField(verbose_name='Yoqilgan kaloriya')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jismoniy faollik',
                'verbose_name_plural': 'Jismoniy faolliklar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveIntegerField(default=25, verbose_name='Yosh')),
                ('height', models.FloatField(default=170, verbose_name="Bo'y (sm)")),
                ('weight', models.FloatField(default=70, verbose_name='Vazn (kg)')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], default='male', max_length=10, verbose_name='Jins')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Kam harakatli (ofis ishi)'), ('light', 'Engil faol (haftada 1-3 kun sport)'), ('moderate', "O'rtacha faol (haftada 3-5 kun sport)"), ('very_active', 'Juda faol (haftada 6-7 kun sport)'), ('extra_active', 'Jismoniy mehnat / professional sport')], default='moderate', max_length=20, verbose_name='Faollik darajasi')),
                ('goal', models.CharField(choices=[('lose', "Vazn yo'qotish"), ('maintain', 'Vaznni saqlash'), ('gain', 'Vazn orttirish')], default='maintain', max_length=10, verbose_name='Maqsad')),
                ('target_weight', models.FloatField(blank=True, null=True, verbose_name='Maqsad vazn (kg)')),
                ('daily_calorie_goal', models.IntegerField(default=2000, verbose_name='Kunlik kaloriya maqsadi')),
                ('daily_water_goal', models.IntegerField(default=8, verbose_name='Kunlik suv maqsadi (stakan)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.CreateModel(
            name='FoodLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Taom like',
                'unique_together': {('user', 'food')},
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('glasses', models.PositiveIntegerField(default=0, verbose_name='Stakan soni')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Suv iste'moli",
                'verbose_name_plural': "Suv iste'mollari",
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Vazn (kg)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Sana')),
                ('notes', models.TextField(blank=True, verbose_name='Eslatma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vazn yozuvi',
                'verbose_name_plural': 'Vazn yozuvlari',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
